<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Repository\BusinessData\" />
    <Folder Include="Repository\Security\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entity\CakeOs.Entity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.13" />
  </ItemGroup>

</Project>
